steps:

- name: 'composer/composer'
  args: [ 'install' ]
  dir: "php"
  id: "php-composer"

- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/container-builder-test', '.' ]
  id: "docker-build"
  waitFor:
  - "php-composer"

images:
- 'gcr.io/$PROJECT_ID/container-builder-test'
