steps:

- name: 'composer/composer'
  args: [ 'install' ]
  dir: "php"
  id: "php-composer"

- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-f', 'Dockerfile-php', '-t', 'gcr.io/$PROJECT_ID/php', '.' ]
  id: "docker-build"
  waitFor:
  - "php-composer"

- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-f', 'Dockerfile-nginx', '-t', 'gcr.io/$PROJECT_ID/nginx', '.' ]
  id: "docker-build"

- name: gcr.io/cloud-builders/gsutil
  args: ["cp", "gs://${PROJECT_ID}/production.kubeconfig", "/workspace/kubeconfig"]

- name: "gcr.io/google_containers/hyperkube:v1.5.3"
  env: ["KUBECONFIG=/workspace/kubeconfig"]
  entrypoint: "/hyperkube"
  args: ["kubectl", "apply", "-f", "/workspace/production"]

images:
- 'gcr.io/$PROJECT_ID/php'
- 'gcr.io/$PROJECT_ID/nginx'
