apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cbt
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: cbt
    spec:
      containers:
        - image: gcr.io/container-builder-test-161511/php
          name: cbt
          imagePullPolicy: "Always"
        - image: gcr.io/container-builder-test-161511/nginx
          name: nginx
          imagePullPolicy: "Always"
          ports:
          - containerPort: 80
            name: nginx
